---
title: 'Gene set testing for Illumina HumanMethylation Arrays'
subtitle: "Exploring minimum and maximum gene set size parameters for methylGSA"
author: "Jovana Maksimovic, Alicia Oshlack and Belinda Phipson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, results='hide'}
library(here)
library(reshape2)
library(ggplot2)
library(glue)
library(tidyverse)
library(patchwork)
library(gt)
```

# Explore effect of minimum and maximum gene set size parameters

## Load data

We have run all three methylGSA methods, testing GO categories, on the three blood cell contrasts for the following combinations of minimum and maximum gene set size parameters: 

```{r}
params <- data.frame(minsize = c(1:5, rep(5, 5)),                      
                     maxsize = c(rep(5000, 5), seq(7000, 18000, by = 2750)))
params
```

Read in the results of all the analyses.

```{r}
inFile <- here("output/methylgsa-params/methylGSA-param-sweep.rds")
dat <- readRDS(inFile)
```

## Examine results

```{r, fig.width=6, fig.height=20, message=FALSE, warning=FALSE}
dat %>% mutate(combo = glue("{minsize}.{maxsize}")) %>%
    group_by(method, contrast, combo) %>%
    mutate(rank = 1:n()) %>%
    filter(rank <= 20) %>% 
    group_by(method, contrast) %>%
    mutate(params = factor(combo),
           params = factor(params,
                           levels = levels(params)[order(c(1:4,8:10,5:7))])) -> sub

methods <- c("glm", "gsea", "ora")
p <- vector("list", length(methods))

for(i in 1:length(methods)){
    sub %>% filter(method == methods[i]) -> subMeth
    
    p[[i]] <- ggplot(subMeth, aes(x=rank, y=Size)) +
        geom_bar(stat = "identity", position = "dodge") +
        facet_grid(params ~ contrast, scales = "free_y") +
        theme(legend.position = "bottom") +
        labs(x = "Rank", y = "No. genes in set") +
        ggtitle(methods[i])
}

p[[1]] / p[[2]] / p[[3]]
```


```{r}
# sub %>% gt()
# 
#     fmt_number(columns = vars(mean, mins), decimals = 2) %>%
#     cols_label(
#         mean = md("**Seconds**"),
#         mins = md("**Minutes**"),
#         method = md("**Method**")
#         ) %>%
#   tab_header(
#     title = md("**Average run-time across all contrasts**"),
#     subtitle = md("Using Broad MSigDB gene sets from `ChAMP` package")
#     ) %>%
#   tab_source_note(md("_*All methods were run on a single core._"))
```

