---
title: 'Gene set testing for Illumina HumanMethylation Arrays'
subtitle: "Exploring the biases on EPIC arrays "
author: "Jovana Maksimovic, Alicia Oshlack and Belinda Phipson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=10000)
```

```{r, message=FALSE, warning=FALSE, results='hide'}
library(here)
library(glue)
library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
library(missMethyl)
library(org.Hs.eg.db)
library(GO.db)
library(patchwork)
library(grid)
library(ggplot2)
library(tibble)
library(dplyr)
source(here("code/utility.R"))
```

## Array properties

Get the array annotation data.

```{r}
ann <- loadAnnotation(arrayType="EPIC")
flatAnn <- loadFlatAnnotation(ann)
```

```{r}
dat <- data.frame(table(table(flatAnn$entrezid)))
numCpgsPerGene <- as.vector(table(flatAnn$entrezid))
med <- median(numCpgsPerGene)
mod <- getMode(numCpgsPerGene)
  
f1a <- ggplot(dat, aes(x=Var1, y=Freq)) +
  geom_segment(aes(x=Var1, xend=Var1, y=0, yend=Freq), color="darkgrey") +
  geom_point( color="black", size=1) +
  geom_vline(xintercept = med, linetype = "dashed", color = "black") +
  annotate("text", x = med + 2, label=glue("Median = {med}"), y=720, colour="black", 
            size = 3, hjust="left") +
  geom_vline(xintercept = mod, linetype = "dashed", color = "black") +
  annotate("text", x = mod + 2, label=glue("Mode = {mod}"), y=780, colour="black", 
            size = 3, hjust="left") +
  scale_x_discrete(breaks = c(1,10,20,30,45,55,70,80,90,100,120,135,150,160,180,
                              200,215,250,330,429,1485)) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  xlab("No. CpGs per gene") +
  ylab("Frequency")

f1a
```

```{r}
ann450 <- loadAnnotation("450k")
flatAnn450 <- loadFlatAnnotation(ann450)

dat <- cpgsEgGoFreqs(flatAnn)
dat$Array <- "EPIC"

tmp <- cpgsEgGoFreqs(flatAnn450)
tmp$Array <- "450k"

dat <- bind_rows(dat, tmp)

dat %>% 
    group_by(Array, GO) %>%
    summarise(avg = mean(Freq)) -> datSum

maxEPIC <- max(datSum$avg[datSum$Array == "EPIC"])
max450 <- max(datSum$avg[datSum$Array == "450k"])

bw <- 2
platform <- c("EPIC" = "blue", "450k" = "red")
f1c <- ggplot(datSum, aes(x=avg)) +
    geom_histogram(dat = subset(datSum, Array == "450k"),
                   alpha = 0.5, aes(fill = "450k"), binwidth = bw) +
    geom_histogram(dat = subset(datSum, Array == "EPIC"),
                   alpha = 0.5, aes(fill = "EPIC"), binwidth = bw) +
    geom_vline(xintercept = max450, linetype="dashed", colour = "red") +
    geom_vline(xintercept = maxEPIC, linetype="dashed", colour = "blue") +
    labs(x="Mean no. CpGs per gene per GO category", y = "Frequency",
         fill = "Platform") +
    annotate("text", x = maxEPIC - 4, label=glue("Max. EPIC = {maxEPIC}"),
             y = 1500, colour="blue", size = 3, hjust="right") +
    annotate("text", x = max450 - 4, label=glue("Max. 450k = {max450}"),
             y = 2500, colour="red", size = 3, hjust="right") +
    scale_fill_manual(values = platform)

f1c
```

```{r}
dat <- data.frame(table(table(flatAnn$cpg)))
dat$Split <- ifelse(dat$Freq > 2500, "A",
                    ifelse(dat$Freq < 2500 & dat$Freq > 65,"B","C"))

a <- ggplot(dat[dat$Split == "A",], aes(x=Var1, y=Freq)) +
    geom_bar(stat = "identity") +
    theme(axis.title.x = element_blank(),
          axis.text.y=element_text(angle=90, hjust=0.5)) +
    ylab("Frequency")

b <- ggplot(dat[dat$Split == "B",], aes(x=Var1, y=Freq)) +
    geom_bar(stat = "identity") +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank())

c <- ggplot(dat[dat$Split == "C",], aes(x=Var1, y=Freq)) +
    geom_bar(stat = "identity") +
    theme(axis.title.x=element_blank(),
          axis.title.y = element_blank())

f1d <- a + b + c + plot_layout(widths = c(1,2,6)) +
    plot_annotation(caption = "No. genes mapped to a CpG",
                    theme = theme(plot.caption = element_text(hjust = 0.5,
                                                              size = 12)))
f1d
```

```{r, fig.width=10, fig.height=8}
load(here("data/input.RData"))
sigCpg <- rownames(limma::topTreat(tfit, coef = "CD4vCD8", num = 5000)) 
allCpg <- rownames(tfit)

layout <- "
AABB
CCDD
"
#old_par <- par(mar = c(0, 2, 0, 0), bg = NA)
# (f1a | wrap_elements(panel = ~gometh(sigCpg, all.cpg = allCpg, plot.bias = TRUE, 
#                              anno = ann), clip = FALSE)) /
# (f1c | wrap_elements(f1d)) #+ plot_layout(design = layout)
#par(old_par)
(f1a | plot_spacer()) /
(f1c | wrap_elements(panel = f1d))# + plot_layout(design = layout)

```

